apps/cic_api/urls.py
#  Copyright (c) 2022,
#  CIC Checker
#  __author = "cuong"
#  __date_time = "7/24/22, 5:33 PM"


from django.urls import path, include
from rest_framework import routers
from .views import SingleCheckViewSet, MultiCheckViewSet

router = routers.DefaultRouter()
router.register(r"single", SingleCheckViewSet, basename="single-check")
router.register(r"multi", MultiCheckViewSet, basename="multi-check")

urlpatterns = [
    path("", include(router.urls)),
]

apps/cic_auth/urls.py
#  Copyright (c) 2022,
#  CIC Checker
#  __author = "cuong"
#  __date_time = "7/24/22, 10:02 AM"

from django.urls import path, include
from django.contrib.auth import views as auth_views


app_name = "auth"
urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="cic_auth/login.html"),
        name="login",
    ),
    path("", include("django.contrib.auth.urls")),
]

apps/cic_cms/urls.py
#  Copyright (c) 2022,
#  CIC Checker
#  __author = "cuongvu"
#  __date_time = "7/30/22, 9:19 PM"
#

from django.urls import path

from apps.cic_cms.views.dashboard import DashboardView

app_name = "cms"
urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
]

apps/cic_tool/urls.py
from django.urls import path

from apps.cic_tool.views import SingleView, MultipleView

app_name = "tool"
urlpatterns = [
    path("single-checks/", SingleView.as_view(), name="single"),
    path("multiple-checks/", MultipleView.as_view(), name="multiple"),
]

configs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("apps.cic_core.routers")),
    path("admin/", admin.site.urls),
]

apps/cic_account/models.py
from django.db import models


class CicAccount(models.Model):
    user_name = models.CharField(blank=False, max_length=255, db_index=True)
    password = models.CharField(blank=False, max_length=255)
    is_active = models.BooleanField(default=False)
    is_live = models.BooleanField(default=False, unique=True)

    def __str__(self):
        return f"{self.user_name} - {'live' if self.is_live else 'die'}"

    class Meta:
        db_table = "cic_accounts"
        unique_together = ("user_name", "password")

apps/cic_cms/models.py
from django.db import models

# Create your models here.

apps/cic_tool/models.py
from django.db import models

# Create your models here.

apps/cic_account/views.py
from django.shortcuts import render

# Create your views here.

apps/cic_api/views/multi.py
#  Copyright (c) 2022,
#  CIC Checker
#  __author = "cuong"
#  __date_time = "7/24/22, 5:43 PM"

from rest_framework import viewsets, status
from rest_framework.response import Response

from apps.cic_tool.services.single import SingleService


class MultiCheckViewSet(viewsets.ViewSet):
    def list(self, request):
        init_data = SingleService().get_init_data()
        return Response(data=init_data, status=status.HTTP_200_OK)

apps/cic_api/views/single.py
#  Copyright (c) 2022,
#  CIC Checker
#  __author = "cuong"
#  __date_time = "7/24/22, 5:41 PM"

from rest_framework import viewsets, status
from rest_framework.response import Response

from apps.cic_tool.services.single import SingleService


class SingleCheckViewSet(viewsets.ViewSet):
    def list(self, request):
        init_data = SingleService().get_init_data()
        return Response(data=init_data, status=status.HTTP_200_OK)

apps/cic_auth/views/user_account.py
#  Copyright (c) 2022,
#  CIC Checker
#  __author = "cuongvu"
#  __date_time = "7/31/22, 12:30 PM"
#
from django.views import generic

from apps.cic_cms.views import BaseCmsView


class UserManageView(BaseCmsView, generic.TemplateView):
    template_name = "cic_auth/account-manage.html"

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        return super().get_context_data(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

apps/cic_cms/views/dashboard.py
#  Copyright (c) 2022,
#  CIC Checker
#  __author = "cuongvu"
#  __date_time = "7/30/22, 9:11 PM"
#

from django.views import generic

from apps.cic_cms.views import BaseCmsView


class DashboardView(BaseCmsView, generic.TemplateView):
    template_name = "cic_cms/dashboard.html"

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        data = super().get_context_data(*args, **kwargs)
        return data

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)

        return response

apps/cic_cms/views/index.py
#  Copyright (c) 2022,
#  CIC Checker
#  __author = "cuongvu"
#  __date_time = "7/30/22, 9:20 PM"
#
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from apps.cic_core.mixins.base import BaseViewMixin


class IndexView(BaseViewMixin, generic.TemplateView):
    def dispatch(self, request, *args, **kwargs):
        is_authenticated = request.user and request.user.is_authenticated
        redirect_url = reverse_lazy("cms:dashboard")
        if not is_authenticated:
            redirect_url = reverse_lazy("login")

        return HttpResponseRedirect(redirect_url)

apps/cic_tool/views/multiple.py
from django.http.response import Http404
from django.views import generic

# Create your views here.
from apps.cic_cms.views import BaseCmsView


class MultipleView(BaseCmsView, generic.TemplateView):
    template_name = "cic_tool/multiple.html"

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)

        return response

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            pass

        return Http404()

apps/cic_tool/views/single.py
from django.http.response import Http404
from django.views import generic

# Create your views here.
from apps.cic_cms.views import BaseCmsView


class SingleView(BaseCmsView, generic.TemplateView):
    template_name = "cic_tool/single.html"

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)

        return response

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            pass

        return Http404()

apps/cic_auth/templates/cic_auth/account-manage.html
{% extends 'cms.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item active"><a {% url 'auth:user-management' %}>Quản Lý User</a></li>
{% endblock breadcrumbs %}

{% block cms_content %}
    <div class="row">
        <h1>Quản lý user</h1>
    </div>
{% endblock cms_content %}

apps/cic_auth/templates/cic_auth/login.html
{% extends 'base.html' %}
{% block body_content %}
    <div class="login-form-bg h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100">
                <div class="col-xl-6">
                    <div class="form-input-content">
                        <div class="card login-form mb-0">
                            <div class="card-body pt-5">
                                <div class="text-center"><h4>Rosella</h4></div>

                                <form class="mt-5 mb-5 login-input" method="POST">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label>
                                            <input type="text" class="form-control" placeholder="Username"
                                                   name="username">
                                        </label>
                                    </div>
                                    <div class="form-group">
                                        <label>
                                            <input type="password" class="form-control" placeholder="Password"
                                                   name="password">
                                        </label>
                                    </div>
                                    <button class="btn login-form__btn submit w-100" type="submit">Sign In</button>
                                </form>
                                <p class="mt-5 login-form__footer">Dont have account? <a href="{% url 'login' %}"
                                                                                         class="text-primary">Sign
                                    Up</a> now</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body_content %}

apps/cic_cms/templates/cic_cms/dashboard.html
{% extends "cms.html" %}

{% block breadcrumbs %}
    <li class="breadcrumb-item active"><a {% url 'cms:dashboard' %}>Dashboard</a></li>
{% endblock breadcrumbs %}

{% block cms_content %}
    <div class="row">
        {% for product in products %}
            <div class="col-lg-6 col-sm-6">
                <div class="card gradient-{{ forloop.counter }}">
                    <div class="card-body">
                        <h3 class="card-title text-white">{{ product.name }}</h3>
                        <div class="d-inline-block">
                            <h2 class="text-white">{{ product.count }}</h2>
                            <p class="text-white mb-0">Jan - March 2019</p>
                        </div>
                        <span class="float-right display-5 opacity-5"><i class="fa fa-address-card"></i></span>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock cms_content %}

apps/cic_single/templates/cic_single/_import.html
<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Bootstrap Input File</h4>
            <div class="basic-form">
                <form action="{% url 'import_data' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="file" class="form-control-file" name="excel_file">
                        <button type="submit">Import</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% for data in excel_data %}
    <div>{{ data }}</div>
{% endfor %}

apps/cic_tool/templates/cic_tool/_import.html
<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Bootstrap Input File</h4>
            <div class="basic-form">
                <form>
                    <div class="form-group">
                        <input type="file" class="form-control-file" name="excel_file">
                        <button type="submit">Import</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

apps/cic_tool/templates/cic_tool/multiple.html
{% extends 'cms.html' %}
{% load static %}

{% block breadcrumbs %}
    <li class="breadcrumb-item active"><a {% url 'tool:single' %}>Check Hàng Loạt</a></li>
{% endblock breadcrumbs %}

{% block cms_content %}
    <div class="row">
        <h1>Check Hàng Loạt</h1>
    </div>
{% endblock cms_content %}

apps/cic_tool/templates/cic_tool/single.html
{% extends 'cms.html' %}
{% load static %}

{% block breadcrumbs %}
    <li class="breadcrumb-item active"><a {% url 'tool:single' %}>Check Đơn</a></li>
{% endblock breadcrumbs %}

{% block cms_content %}
    <div class="row">
        <h1>Check Đơn</h1>
    </div>
{% endblock cms_content %}

{% block vendor-js %}
    <script src="{% static 'site/js/cic/checker.single.js' %}"></script>
{% endblock vendor-js %}

apps/templates/_footer.html
<div class="footer">
    <div class="copyright">
        <p>Copyright &copy;</p>
    </div>
</div>

apps/templates/_header.html
{% load static %}
<div class="header">
    <div class="header-content clearfix">

        <div class="nav-control">
            <div class="hamburger">
                <span class="toggle-icon"><i class="icon-menu"></i></span>
            </div>
        </div>
        <div class="header-left">
            <div class="input-group icons">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-transparent border-0 pr-2 pr-sm-3" id="basic-addon1"><i
                            class="mdi mdi-magnify"></i></span>
                </div>
                <input type="search" class="form-control" placeholder="Search Dashboard" aria-label="Search Dashboard">
                <div class="drop-down   d-md-none">
                    <form action="#">
                        <label>
                            <input type="text" class="form-control" placeholder="Search">
                        </label>
                    </form>
                </div>
            </div>
        </div>
        <div class="header-right">
            <ul class="clearfix">
                {% if user.is_superuser %}

                    <li class="icons dropdown">
                        {{ user.email }}
                    </li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li class="icons dropdown">
                        <div class="user-img c-pointer position-relative" data-toggle="dropdown">
                            <span class="activity active"></span>
                            <img src="{% static 'site/images/user/1.png' %}" height="40" width="40" alt="">
                        </div>
                        <div class="drop-down dropdown-profile   dropdown-menu">
                            <div class="dropdown-content-body">
                                <ul>
                                    <li>
                                        <a href="app-profile.html"><i class="icon-user"></i>
                                            <span>Profile</span></a>
                                    </li>
                                    <hr class="my-2">
                                    <li>
                                        <a href="page-lock.html"><i class="icon-lock"></i> <span>Lock Screen</span></a>
                                    </li>
                                    <li><a href="{% url 'auth:logout' %}"><i class="icon-key"></i> <span>Logout</span></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</div>

apps/templates/_meta.html
{% load static %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content = "width = device-width, initial-scale = 1.0, minimum-scale = 1, maximum-scale = 1, user-scalable = no, shrink-to-fit=no" />
<meta name="author" content="CIC Checker">
<meta name="format-detection" content="telephone=no">
<meta name="description" content="Check CIC">

apps/templates/_nav-header.html
{% load static %}
<div class="nav-header">
    <div class="brand-logo">
        <a href="{% url "cms:dashboard" %}">
            <b class="logo-abbr"><img src="{% static 'site/images/logo.png' %}" alt=""> </b>
            <span class="logo-compact"><img src="{% static 'site/images/logo-compact.png' %}" alt=""></span>
            <span class="brand-title">
            <img src="{% static 'site/images/logo-text.png' %}" alt="">
            </span>
        </a>
    </div>
</div>

apps/templates/_siderbar.html
<div class="nk-sidebar">
    <div class="nk-nav-scroll">
        <ul class="metismenu" id="menu">
            {% for menu_item in menu_items %}
                <li>
                    <a href="{{ menu_item.get_url }}" aria-expanded="false">
                        <i class="{{ menu_item.get_icon }}"></i>
                        <span class="nav-text">{{ menu_item.get_name }}</span>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

apps/templates/base.html
{% load static compress i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    {% include "_meta.html" %}
    {% block meta %}
    {% endblock meta %}
    {% include "_stylesheet.html" %}
    {% block css-uncompress %}
    {% endblock css-uncompress %}
    {% compress css %}
        {% block vendor-css %}
            <link type="text/x-scss" href="{% static '/site/sass/base.scss' %}" rel="stylesheet">
        {% endblock vendor-css %}
    {% endcompress %}
    {% block title %}
        <title>{{ title|default:"Website Django Template"|capfirst }}</title>
    {% endblock title %}

</head>
<body>
{% block body_content %}
{% endblock body_content %}

<script type="text/javascript" src="{% static 'site/plugins/common/common.min.js' %}"></script>
<script type="text/javascript" src="{% static 'site/js/custom.min.js' %}"></script>
{% compress js %}
    <script type="text/javascript" src="{% static 'site/js/settings.js' %}"></script>
    <script type="text/javascript" src="{% static 'site/js/gleek.js' %}"></script>
    {% block vendor-js %}
    {% endblock vendor-js %}
{% endcompress %}
</body>
</html>

apps/templates/cms.html
{% extends 'base.html' %}

{% block body_content %}
    <div id="main-wrapper">
        {% include '_nav-header.html' %}
        {% include '_header.html' %}
        {% include '_siderbar.html' %}
        <div class="content-body">
            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a class="link-primary" href="{% url 'cms:dashboard' %}">Home</a></li>
                        {% block breadcrumbs %}
                        {% endblock breadcrumbs %}
                    </ol>
                </div>
            </div>
            <div class="container-fluid">
                {% block cms_content %}
                {% endblock cms_content %}
            </div>
        </div>
        {% include '_footer.html' %}
    </div>
{% endblock body_content %}